stages:
  - test
  #- build
  - deploy

#cache:
  #paths:
    #- build/

test:
  stage: test
  tags:
    - docker
  script:
    - docker run --rm nginx:alpine echo "testing"

deploy:
  stage: deploy
  only:
    - master
  tags:
    - docker
  script:
    - git submodule update
    - docker-compose up -d --build
