variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - test
  #- build
  - deploy

#cache:
  #paths:
    #- build/

test:
  stage: test
  tags:
    - docker
  script:
    - docker run --rm nginx:alpine echo "testing"

deploy:
  stage: deploy
  only:
    - master
  tags:
    - docker
  script:
    #- git lfs install
    #- git submodule init
    #- git submodule update
    #- git submodule status
    - docker-compose up -d --build
