version: "3"
services:

  mosquitto:
    image: eclipse-mosquitto 
    volumes:
      - /mosquitto/data
      - /mosquitto/log

  mqtt-client:
    image: efrecon/mqtt-client
    command: sub -h mosquitto -t "#" -v 

  activity-detector:
    image: activity-detector
    environment:
        SPRING_PROFILES_ACTIVE: snapshot
        TZ: "Europe/Berlin"
    ports:
        - "8001:8000"

  zookeeper:
    image: confluentinc/cp-zookeeper:5.2.1
    hostname: zookeeper
    ports:
        - "2181:2181"
    environment:
        ZOOKEEPER_CLIENT_PORT: 2181
        TZ: "Europe/Berlin"

  kafka:
    image: confluentinc/cp-kafka:5.2.1
    hostname: kafka
    ports:
        - "9092:9092"
        - "29092:29092"
    environment:
        KAFKA_BROKER_ID: 1
        KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
        KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
        KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
        KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
        KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
        TZ: "Europe/Berlin"
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - ./kafka:/kafka
        - ./kafka-plugins:/usr/share/java/kafka-extra
        - ./kafka-config:/kafka-config
    depends_on:
        - zookeeper
