version: '3'

services:
  redis:
    image: redis:latest
    command: redis-server
    ports:
      - "127.0.0.1:6379:6379"
      - "127.0.0.1:6380:6380"
  web:
    build: ./experiencesampling
    command: python manage.py runserver 0.0.0.0:8002
    ports:
      - "127.0.0.1:18002:8002"
#  worker_channels:
#
#    build: .\experiencesampling
#    command: python manage.py runworker channels
#    volumes:
#      - .:\code
#    links:
#      - redis
  channels:
    build: ./experiencesampling
    command: daphne -p 8001 experiencesampling.asgi:application
    ports:
      - "127.0.0.1:18001:8001"
    links:
     - redis
