{
 "title": "Kafka Overview",
 "description": "Kafka resource usage and throughput",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Outgoing Bytes Sum",
   "type": "singlestat",
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_producer_outgoing_byte_total)",
     "legendFormat": "{{clientId}}"
    }
   ]
  },
  {
   "title": "Messages send Sum",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_producer_record_send_total)",
     "legendFormat": "{{clientId}}"
    }
   ]
  },
  {
   "title": "Worker Connector Count",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "kafka_connect_worker_connector_count"
    }
   ]
  },
  {
   "title": "Worker Task Count",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "kafka_connect_worker_task_count"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short", "label": "Cores" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"kafka\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "JVM Memory Used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 3 },
   "yaxes": [
    { "format": "bytes", "label": "Memory" }
   ],
   "targets": [
    {
     "expr": "sum without(area)(jvm_memory_bytes_used{job=\"kafka\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Time spent in GC",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 3 },
   "yaxes": [
    { "format": "percentunit", "label": "% time in GC" }
   ],
   "targets": [
    {
     "expr": "sum without(gc)(rate(jvm_gc_collection_seconds_sum{job=\"kafka\"}[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Record send Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short", "label": "Records/s" }
   ],
   "targets": [
    {
     "expr": "kafka_producer_record_send_rate{clientId=\"connector-producer-mqtt-sensors-0\"}",
     "legendFormat": "{{clientId}}"
    },
    {
     "expr": "kafka_producer_topic_record_send_rate{topic!=\"connect-config\",topic!=\"connect-offsets\",topic!=\"connect-status\"}",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Producer Byte Rates",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "Bps", "label": "Bytes/s" }
   ],
   "targets": [
    {
     "expr": "kafka_producer_outgoing_byte_rate{clientId=\"connector-producer-mqtt-sensors-0\"}",
     "legendFormat": "{{clientId}} (out)"
    },
    {
     "expr": "kafka_producer_incoming_byte_rate{clientId=\"connector-producer-mqtt-sensors-0\"}",
     "legendFormat": "{{clientId}} (in)"
    },
    {
     "expr": "kafka_producer_topic_byte_rate{topic!=\"connect-config\",topic!=\"connect-offsets\",topic!=\"connect-status\"}",
     "legendFormat": "{{topic}} (out)"
    }
   ]
  },
  {
   "title": "Connect Byte Rates",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 10 },
   "yaxes": [
    { "format": "Bps", "label": "Bytes/s" }
   ],
   "targets": [
    {
     "expr": "kafka_connect_outgoing_byte_rate",
     "legendFormat": "{{clientId}} (out)"
    },
    {
     "expr": "kafka_connect_incoming_byte_rate",
     "legendFormat": "{{clientId}} (in)"
    }
   ]
  },
  {
   "title": "Records send Total",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "none", "label": "Records" }
   ],
   "targets": [
    {
     "expr": "kafka_producer_record_send_total{clientId=\"connector-producer-mqtt-sensors-0\"}",
     "legendFormat": "{{clientId}}"
    },
    {
     "expr": "kafka_producer_topic_record_send_total{topic!=\"connect-config\",topic!=\"connect-offsets\",topic!=\"connect-status\"}",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Producer Byte Totals",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 17 },
   "yaxes": [
    { "format": "decbytes", "label": "Bytes" }
   ],
   "targets": [
    {
     "expr": "kafka_producer_outgoing_byte_total{clientId=\"connector-producer-mqtt-sensors-0\"}",
     "legendFormat": "{{clientId}} (out)"
    },
    {
     "expr": "kafka_producer_incoming_byte_total{clientId=\"connector-producer-mqtt-sensors-0\"}",
     "legendFormat": "{{clientId}} (in)"
    },
    {
     "expr": "kafka_producer_topic_byte_total{topic!=\"connect-config\",topic!=\"connect-offsets\",topic!=\"connect-status\"}",
     "legendFormat": "{{topic}} (out)"
    }
   ]
  },
  {
   "title": "Connect Byte Totals",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 17 },
   "yaxes": [
    { "format": "decbytes", "label": "Bytes" }
   ],
   "targets": [
    {
     "expr": "kafka_connect_outgoing_byte_total",
     "legendFormat": "{{clientId}} (out)"
    },
    {
     "expr": "kafka_connect_incoming_byte_total",
     "legendFormat": "{{clientId}} (in)"
    }
   ]
  }
 ]
}