{
 "title": "Mosquitto Overview",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    { "expr": "broker_uptime" }
   ]
  },
  {
   "title": "Subscription count",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "broker_subscriptions_count" }
   ]
  },
  {
   "title": "Clients connected",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "broker_clients_connected" }
   ]
  },
  {
   "title": "Transfered data sum",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 12, "y": 0 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "broker_bytes_received + broker_bytes_sent"
    }
   ]
  },
  {
   "title": "Published Messages",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "broker_publish_messages_sent", "legendFormat": "Sent" },
    {
     "expr": "broker_publish_messages_received",
     "legendFormat": "Received"
    }
   ]
  },
  {
   "title": "Transfered Data",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "broker_bytes_sent", "legendFormat": "Sent" },
    { "expr": "broker_bytes_received", "legendFormat": "Received" }
   ]
  },
  {
   "title": "Messages per Minute",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "broker_load_messages_sent_1min", "legendFormat": "Sent" },
    { "expr": "broker_load_messages_sent_1min", "legendFormat": "Received" }
   ]
  },
  {
   "title": "Transferred Data per Minute",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "broker_load_bytes_sent_1min", "legendFormat": "Sent" },
    {
     "expr": "broker_load_bytes_received_1min",
     "legendFormat": "Received"
    }
   ]
  }
 ]
}